### ISSUE TITLE
Support for Coroutine

### ISSUE THREAD

**Issue by jonathan-shemer** [mzipay/Autologging#10]
When using `@traced` on a coroutine, RETURN logs a coroutine object and not the value returned after await.
Could you please add support for `async` methods?

**Comment by mzipay** [comment]
Hi Jonathan,

Yes, this work is already underway - see https://github.com/mzipay/Autologging/issues/8.  I do not yet have a timeline, but I may publish the branch once it is a bit more stable.

**Comment by mzipay** [comment]
Please see [issues/11](https://github.com/mzipay/Autologging/issues/11)
