### ISSUE TITLE
is it possible to use pprint option for logging?

### ISSUE THREAD

**Issue by mas-dse-juremigi** [mzipay/Autologging#15]
would it be possible to include an option to use pprint to format all log output?

**Comment by mzipay** [comment]
Autologging supports any formatting that is configurable via the standard library's `logging` module; if you can do it via a `logging.Formatter`, then you can have that formatting through Autologging.

In short - Autologging will not support specific options related to log formatting as it is not a _replacement_ for `logging`.  It is the caller's responsibility to configure any specialized formatting through the standard configuration mechanism.

Have a look at the sample code on the front page of https://autologging.readthedocs.io/, or at any of the examples in the https://autologging.readthedocs.io/en/latest/examples.html section to see an (admittedly simplified) example of configuring the log entry format.

See also:
https://docs.python.org/3/library/logging.html#formatter-objects
https://docs.python.org/3/library/logging.config.html
