### ISSUE TITLE
Feature request:  Exclude methods

### ISSUE THREAD

**Issue by jdgvt81** [mzipay/Autologging#9]
I'm not sure whether such a request is even feasible, but I'd like to suggest the ability to exclude specific methods from tracing.  Currently, when decorating a class with `@traced`, all methods are traced except for most special methods.  I'd like to exclude specific non-special methods as well.  (I realize it's possible to specifically _include_ only certain methods, but when _all methods, but one_ of a large class need to be traced, for instance, excluding would be much simpler to write.

At this point I can't offer a pull request - I think that's beyond my skill level - but I'll try to look into it.

Thanks!

**Comment by mzipay** [comment]
Hi, this is certainly feasible. Off the top of my head, I would say the easiest way would be to allow a keyword argument (exclude=False) to traced. This would preserve backward compatibility such that `@traced("method_1", "method_2")` would still _include_ those methods, but would allow the inverse semantic like `@traced("method_1", "method_2", exclude=True)`, which would now cause the default method set to be included but "method_1" and "method_2", specifically, to be _excluded_.

I need to take a closer look to determine whether or not it is the best approach, but I agree that the feature, conceptually, should be added. Thanks for the feedback.

**Comment by jdgvt81** [comment]
Maybe all is not well...  when running unfrozen, it has no issues.  But then I froze my application with PyInstaller and I get the following traceback:

```
Traceback (most recent call last):
  File "lac.py", line 484, in main
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\development\python_env\lac_py36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lac_window.py", line 43, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\development\python_env\lac_py36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "query_actiondb.py", line 35, in <module>
TypeError: _traced_noop() got an unexpected keyword argument 'exclude'
```
Prior to this update, the application ran frozen with no issues.  It's almost as if the frozen application doesn't recognize the new version - but I'm not sure how that's possible since I uninstalled autologging prior to installing from this branch.  Any ideas?  I'm happy to provide whatever information I can that might be of help.

**Comment by mzipay** [comment]
It would seem that the frozen app has the no-op traced decorator installed, effectively disabling all tracing. This is fine, though it does identify a bug that I'll need to fix in the release.

Was it your intent to disable all tracing in the frozen app? Or is that unexpected?
(The TypeError itself  is certainly unexpected - and definitely a bug on my end.)

**Comment by mzipay** [comment]
The _traced_noop() TypeError is fixed in 1.3.0b1 if you'd like to give it another try (same branch).

I am hoping to have 1.3.0 released some time this weekend, just need to get the docs updated and run more tests.

**Comment by mzipay** [comment]
The 1.3.0 release just went out.  I am going to leave this issue open until I hear from you that it is working as you expect.

**Comment by mzipay** [comment]
Autologging is now on release 1.3.1.  If there are any further issues related to exclusions, please open a new issue.

**Comment by jdgvt81** [comment]
I was finally able to test this  and yes, it now all works as expected with no issues once frozen.  Thanks again!!

**Comment by mzipay** [comment]
@jdgvt81 Glad to hear.  FYI I have been moving quickly on Autologging recently, and there are likely two be a couple more releases over the next several weeks or so.
